dist: trusty
sudo: required
language: node_js

node_js:
  - "9"

os:
  - linux

addons:
  chrome: stable

env:
  global:
  - LOGS_DIR=/tmp/ngx-mime-build/logs
  - SAUCE_USERNAME=ronnymikalsen
  - SAUCE_ACCESS_KEY=fa5b212d-466a-4e29-b593-957164bfc10b
  - BROWSER_PROVIDER_READY_FILE=/tmp/ngx-mime-build/readyfile

before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install
  - npm install -g mountebank
  - npm install -g webdriver-manager
  - npm install -g protractor
  - npm install -g @angular/cli
  - npm install -g concurrently

before_script:
 - npm prune
 - mkdir -p $LOGS_DIR
 - chmod +x ./scripts/ci/build-and-test.sh
 - chmod +x ./scripts/saucelabs/start-tunnel.sh
 - chmod +x ./scripts/saucelabs/wait-tunnel.sh
 - chmod +x ./scripts/saucelabs/stop-tunnel.sh
 - chmod +x ./integration/scripts/wait-on.sh
 - chmod +x ./integration/scripts/protractor-chrome-headless.sh
 - chmod +x ./integration/scripts/protractor.sh

script:
  - travis_wait 60 ./scripts/ci/build-and-test.sh
