dist: trusty
sudo: required
language: node_js

node_js:
  - "7"

os:
  - linux

addons:
  chrome: stable
  jwt:
    secure: "D9LsbX3nHLl55MXrXdLv6sJse7vEsUTHyxxxJlLwOxSUrlOLuhyE0DrvUVVvOvNjHbwgenmqdGFtQ8Gsx9q+C1psM/VtMoiEViLkxFzczAlElNqoD5nGM9/988aFzaipzvce13m5CjCaEjdZmUepc3JVgY5jFyW949JVOPLY7lZMu6jJgDXX//xZ6SqCZ+y0GSz/zE7nN8VhMceg7/elLeW63A8mROXGfwe4plssQ3JP6QoxlqBeaS97zRytX6b10oaAddtNpuHG53hIa/ZYGIfLvuVKKhdY3WhuuwF9m4/h+xgMbMjAuj1yoFdQ/2TCeORIV2/osuvkVHqZnmge523+endbnOzkaIb1q67v/t6tJ9gHrTz+8lM6Dj3A9Wj129x1fDsrEJOH74e0q+NvO0Qqz8YXLuwbh2boQYhUsgOhsFZ+MdMONa7+bqNUkX8IYyb1Xfj7WgLcuFn0RhwtTIhLFDwDWOBLhmdcvZPGbU3RrGS4m53wq/ZlMzDpwU8eFT+2s1BpYrnLFrTh9kJrL61KycvJgG7xPgS7g64rLFdtyV0wXVBqZ3XdiVzlARG9XABbCHAePPXJV6ggFPThLkU8ZKlgSc/eOTQY30lSrXj/8ws3+/pzgyzypy0Mm10LwkGmL5pBlQsT4q18l9Aj9WvzBzZbiJPukBgw5Rm9bpU="

env:
  global:
  - LOGS_DIR=/tmp/ngx-mime-build/logs
  - SAUCE_USERNAME=ronnymikalsen
  - SAUCE_ACCESS_KEY=fa5b212d-466a-4e29-b593-957164bfc10b
  - BROWSER_PROVIDER_READY_FILE=/tmp/ngx-mime-build/readyfile

before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

before_script:
 - npm prune
 - mkdir -p $LOGS_DIR
 - chmod +x ./scripts/ci/build-and-test.sh
 - chmod +x ./scripts/saucelabs/start-tunnel.sh
 - chmod +x ./scripts/saucelabs/wait-tunnel.sh
 - chmod +x ./scripts/saucelabs/stop-tunnel.sh
 - chmod +x ./integration/scripts/wait-on.sh

script:
  - travis_wait 40 ./scripts/ci/build-and-test.sh
