dist: trusty
sudo: required
language: node_js

node_js:
  - "10"

os:
  - linux

addons:
  chrome: stable

env:
  global:
  - LOGS_DIR=/tmp/ngx-mime-build/logs
  - SAUCE_USERNAME=ronnymikalsen
  - SAUCE_ACCESS_KEY=fa5b212d-466a-4e29-b593-957164bfc10b
  - BROWSER_PROVIDER_READY_FILE=/tmp/ngx-mime-build/readyfile

before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - yarn install

before_script:
 - mkdir -p $LOGS_DIR
 - chmod +x ./scripts/ci/build-and-test.sh
 - chmod +x ./scripts/saucelabs/start-tunnel.sh
 - chmod +x ./scripts/saucelabs/wait-tunnel.sh
 - chmod +x ./scripts/saucelabs/stop-tunnel.sh
 - chmod +x ./apps/integration-e2e/scripts/wait-on.sh

script:
  - travis_wait 60 ./scripts/ci/build-and-test.sh
